version: '2'
services:
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp-lino
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./data:/home/lino/"
      - "./passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: lino
      FTP_USER_PASS: lzamora
      FTP_USER_HOME: /home/lino
    restart: always